---
- hosts: harbux-node1
  become: yes
  tasks:
    - name: Install the latest version of  Apache
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Install firewald package
      ansible.builtin.yum:
        name: firewalld
        state: latest


    - name: STart httpd and firewalld
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Enable and Start firewalld service
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: write the custom content
      copy:
        content: "Hello World! \n"
        dest: /var/www/html/index.html

    - name: Adding the  exception in firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

- name: Verify the web page
  hosts: localhost
  tasks:
   - name: Test
     uri:
       url: http://localhost
     register: result

   - name: Result display
     debug:
       var: result.status
