---
- hosts: harbux-node1
  become: yes
  tasks:
    - name: Install the latest version of  Apache
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Install firewald package
      ansible.builtin.yum:
        name: firewalld
        state: latest


    - name: STart httpd and firewalld
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Enable and Start firewalld service
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: write the custom content
      copy:
        content: "Hello World! \n"
        dest: /var/www/html/index.html

    - name: Add exception in firewall for http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: Verify the web page is accessible locally
      uri:
        url: http://localhost
      register: result

    - name: Display verification result
      debug:
        var: result.status


