---
- hosts: harbux-node3
  become: yes
  tasks:
    - name: Install the latest packages
      ansible.builtin.yum:
        name:
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
          - firewalld
        state: latest

    - name: write the custom content
      copy:
        content: "Test Lamp Stack! \n"
        dest: /var/www/html/index.html



    - name: Enable and  STart httpd
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Enable and Start Mariadb service
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started

    - name: Enable and Start firewalld service
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started


    - name: Adding the  exception in firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

- name: Verify the Test page
  hosts: localhost #harbux-node1
  tasks:
   - name: access page
     uri:
       url: http://harbux-node3
       status_code: 200
     register: result

   - name: Result display
     debug:
       var: result.status


